name: 🐛 Bug Report
description: Report a bug or unexpected behavior in FSL Continuum
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        Thanks for reporting! This will automatically create a Linear Epic with sub-issues and log to blockchain.
        
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: The FSL pipeline failed when...
    validations:
      required: true
      
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The pipeline should...
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, it...
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (blocks production)
        - High (major feature broken)
        - Medium (feature partially broken)
        - Low (minor issue)
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output
      render: shell
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment details
      value: |
        - OS: 
        - Runner: Self-hosted / GitHub-hosted
        - FSL Version: 
        - Browser: 
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
        - label: I have included reproduction steps
          required: true
        - label: I have checked blockchain audit logs
          required: false
